__title__ = 'hugging_py_face'
__package_name__ = 'hugging_py_face'
__version__ = '0.0.1'
__description__ = "Hugging-Py-face, the Python client for the Hugging Face Inference API."
__email__ = "minurapunchihewa17@gmail.com"
__author__ = 'Minura Punchihewa'
__github__ = 'https://github.com/MinuraPunchihewa/mindsdb-text-to-sql'
__pypi__ = ''
__license__ = ''
__copyright__ = ''